

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
