GET http://127.0.0.1:3000/api/device
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNmU3MjE5ZS1kYTQ4LTQ4ZjQtYTk3NS03ODRmYWYxZjZlOGUiLCJlbWFpbCI6InRlc3RAdGVzdGVzZW4ubm8iLCJyb2xlcyI6WyJBRE1JTiJdLCJuYW1lIjoiVGVzdCBUZXN0ZXNlbiIsImlhdCI6MTcyNDY3NjUwNywiZXhwIjoxNzI0NjgwMTA3fQ.zo7qu4PXhfWNrNBnUIU7nIlr6tylaN8FElcJpi4jD2s
