GET http://127.0.0.1:3000/api/device/skjetlein-skjerm/ip

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOTcyZGY4MC02Yjk0LTQxMzYtODEzNy1hOTNkMjY4Y2FkMWEiLCJlbWFpbCI6ImFkbWluQHRlc3Rlc2VuLm5vIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIl0sIm5hbWUiOiJUZXN0IFRlc3Rlc2VuIiwiaWF0IjoxNzI1MzY5MzgxLCJleHAiOjE3MjUzNzI5ODF9.T8B4psuvS06xIyVYVo_YGSNgBlMYWf6qSBZuXkNs_Jw
