PUT http://127.0.0.1:3000/api/device/skjetlein-skjerm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOTcyZGY4MC02Yjk0LTQxMzYtODEzNy1hOTNkMjY4Y2FkMWEiLCJlbWFpbCI6ImFkbWluQHRlc3Rlc2VuLm5vIiwicm9sZXMiOlsiU1VQRVJfQURNSU4iLCJVU0VSIl0sIm5hbWUiOiJUZXN0IFRlc3Rlc2VuIiwiaWF0IjoxNzI1MzY5MTI1LCJleHAiOjE3MjUzNzI3MjV9.d34fNjAFrLPLYrjwhaiwPu95Yt43nIHUbtgjxa3SeJg

{
  "description": "ayylmao"
}
